rbac.create: true
controller.publishService.enabled: true
#controller.service.type: NodePort



controller:
  healthStatus: true
  nginxStatus:
    enable: true
    allowCidrs: "127.0.0.1,0.0.0.0"
  service:
    type: NodePort
    annotations:
      kubernetes.io/ingress.class: nginx
